site_name: HotelApp Clean Code Repository
site_description: Documentación del repositorio de código limpio de HotelApp.
site_author: Alberto Escobar Taborda, Sanet Correa Castaño, Nicolas Peña

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # modo oscuro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]



nav:
  - Inicio: index.md
  - Inicio Rápido: getting-started.md
  - Guía de Usuario:
      - Comandos CLI: commands.md
      - Persistencia: persistence.md
  - Arquitectura: architecture.md
  - Referencia: reference.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
