from typing import Protocol


class Storage(Protocol):
    """
    Protocol that defines the interface for a storage system.
    """

    def get_all_users(self) -> list[dict]: ...
    def get_user_by_id(self, user_id: int) -> dict | None: ...
    def create_user(self, data: dict) -> dict: ...
    def update_user(self, user_id: int, data: dict) -> dict: ...
    def delete_user(self, user_id: int) -> None: ...

    def get_all_rooms(self) -> list[dict]: ...
    def get_room_by_id(self, room_id: str) -> dict | None: ...
    def create_room(self, data: dict) -> dict: ...
    def update_room(self, room_id: str, data: dict) -> dict: ...
    def delete_room(self, room_id: str) -> None: ...

    def get_history_by_user(self, user_id: int) -> list[dict]: ...
    def create_history(self, data: dict) -> dict: ...
    def delete_history(self, history_id: int) -> None: ...