name: Deploy Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - name: install dependencies
        run: |
          uv add mkdocs-material mkdocs mkdocstrings[python]

      - name: Deply Documentation
        run: |
          uv run mkdocs gh-deploy --force
